import { useState, useEffect, useCallback } from 'react'
import { useTranslation } from 'react-i18next'
import { useAuth } from '../../context/AuthContext'
import { getMyPrescriptions } from '../../services/prescriptions'
import { toast } from 'react-toastify'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'

function statusStyle(status, t) {
  if (status === 'CANCELLED') return { color: '#B91C1C', bg: 'rgba(239,35,60,0.08)', label: t('prescriptions.statusCancelled') }
  if (status === 'SUPERSEDED') return { color: 'var(--gray-500)', bg: 'var(--gray-100)', label: t('prescriptions.statusReplaced') }
  return { color: '#16A34A', bg: 'rgba(34,197,94,0.08)', label: t('prescriptions.statusActive') }
}

/** Build a printable text version of a prescription for download. */
function toPlainText(rx) {
  const lines = []
  lines.push('MediBook — Prescription')
  lines.push(`Reference: #RX-${String(rx.id).padStart(5, '0')}`)
  if (rx.issued_at) lines.push(`Issued: ${new Date(rx.issued_at).toLocaleString()}`)
  if (rx.valid_until) lines.push(`Valid until: ${rx.valid_until}`)
  if (rx.diagnosis) lines.push(`Diagnosis: ${rx.diagnosis}`)
  lines.push('')
  lines.push('Medications:')
  ;(rx.prescription_items || []).forEach((it, i) => {
    lines.push(`  ${i + 1}. ${it.drug_name}${it.strength ? ` ${it.strength}` : ''}${it.form ? ` (${it.form})` : ''}`)
    lines.push(`     ${it.dosage} · ${it.frequency} · ${it.duration}${it.quantity ? ` · Qty ${it.quantity}` : ''}`)
    if (it.instructions) lines.push(`     Note: ${it.instructions}`)
  })
  lines.push('')
  lines.push('This is a digital copy generated by MediBook.')
  return lines.join('\n')
}

export default function MyPrescriptions() {
  const { t, i18n } = useTranslation('patient')
  const { user } = useAuth()
  const [items, setItems] = useState([])
  const [loading, setLoading] = useState(true)

  const load = useCallback(async () => {
    try {
      setLoading(true)
      const data = await getMyPrescriptions(user.id)
      setItems(data)
    } catch {
      toast.error(t('prescriptions.loadFailed'))
    } finally {
      setLoading(false)
    }
  }, [user?.id])

  useEffect(() => { if (user) load() }, [user, load])

  function download(rx) {
    const blob = new Blob([toPlainText(rx)], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `prescription-RX-${String(rx.id).padStart(5, '0')}.txt`
    document.body.appendChild(a)
    a.click()
    a.remove()
    URL.revokeObjectURL(url)
  }

  return (
    <div>
      <Navbar />

      <div className="page-header">
        <div className="container">
          <div className="section-badge">{t('prescriptions.badge')}</div>
          <h1 style={{ fontSize: 'clamp(1.6rem, 3vw, 2.2rem)', color: 'white', fontFamily: 'var(--font-display)', position: 'relative', zIndex: 1 }}>
            {t('prescriptions.title')}
          </h1>
        </div>
      </div>

      <div className="container py-5">
        {loading ? (
          <div className="text-center py-5"><div className="spinner-custom" /></div>
        ) : items.length === 0 ? (
          <div className="text-center py-5" style={{ color: 'var(--gray-500)' }}>
            <i className="bi bi-capsule" style={{ fontSize: 40, opacity: 0.4 }} />
            <p className="mt-3">{t('prescriptions.empty')}</p>
          </div>
        ) : (
          <div className="d-flex flex-column gap-3">
            {items.map((rx) => {
              const s = statusStyle(rx.status, t)
              const its = rx.prescription_items || []
              return (
                <div key={rx.id} className="card-custom" style={{ padding: 20 }}>
                  <div className="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-2">
                    <div>
                      <span style={{ fontWeight: 700 }}>#RX-{String(rx.id).padStart(5, '0')}</span>
                      <span style={{ marginLeft: 10, fontSize: 12, padding: '2px 10px', borderRadius: 'var(--radius-full)', color: s.color, background: s.bg }}>
                        {s.label}
                      </span>
                    </div>
                    <span style={{ fontSize: 12, color: 'var(--gray-500)' }}>
                      {rx.issued_at ? new Date(rx.issued_at).toLocaleDateString(i18n.language) : ''}
                    </span>
                  </div>

                  {rx.diagnosis && (
                    <p style={{ fontSize: 13, margin: '0 0 8px' }}>
                      <span style={{ color: 'var(--gray-500)', fontWeight: 500 }}>{t('prescriptions.diagnosis')}</span>{rx.diagnosis}
                    </p>
                  )}

                  <ol style={{ paddingLeft: 18, margin: '0 0 4px' }}>
                    {its.map(it => (
                      <li key={it.id} style={{ fontSize: 13, marginBottom: 6 }}>
                        <strong>{it.drug_name}</strong>
                        {it.strength ? ` ${it.strength}` : ''}{it.form ? ` (${it.form})` : ''}
                        <br />
                        <span style={{ color: 'var(--gray-600)' }}>
                          {it.dosage} · {it.frequency} · {it.duration}{it.quantity ? ` · ${t('prescriptions.qty', { count: it.quantity })}` : ''}
                        </span>
                        {it.instructions && <><br /><em style={{ color: 'var(--gray-500)' }}>{it.instructions}</em></>}
                      </li>
                    ))}
                  </ol>

                  {rx.valid_until && (
                    <p style={{ fontSize: 12, color: 'var(--gray-500)', margin: '4px 0 0' }}>
                      {t('prescriptions.validUntil', { date: rx.valid_until })}
                    </p>
                  )}
                  {rx.status === 'CANCELLED' && rx.cancelled_reason && (
                    <p style={{ fontSize: 12, color: '#B91C1C', margin: '4px 0 0' }}>
                      {t('prescriptions.cancelledReason', { reason: rx.cancelled_reason })}
                    </p>
                  )}

                  {rx.status !== 'CANCELLED' && (
                    <div className="mt-3">
                      <button className="btn-ghost" style={{ fontSize: 13 }} onClick={() => download(rx)}>
                        <i className="bi bi-download me-1" /> {t('prescriptions.download')}
                      </button>
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        )}
      </div>

      <Footer />
    </div>
  )
}
